version: "3.9"
services:
  web:
    container_name: react-web
    build:
      # 이미지 빌드를 수행할 기준 경로
      context: .
      dockerfile: ./web/dockerfile

    # 최초 한번 실행 후 재부팅 시 자동 재실행
    restart: always
    ports:
      - 80:80
