version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./packages/web-server/Dockerfile
    # Container 이름
    container_name: web-server
    # 최초 한번 실행 후 재부팅 시 자동 재실행
    restart: always
    ports:
      - 80:3000
