name: Nodejs CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: NPM Install
      run: npm install
