name: Nodejs CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Git Pull
      run: |
        cd ~/react-for-unity-webgl-test
        git pull

    - name: NPM Install
      run: |
        cd ~/react-for-unity-webgl-test
        npm install
