name: Nodejs CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      GIT_DIR: '~/react-for-unity-webgl-test'

    runs-on: self-hosted
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Git Pull
      run: |
        cd ${{ env.GIT_DIR }}
        git pull

    - name: NPM Install
      run: |
        cd ${{ env.GIT_DIR }}
        npm install
