# Note: 상위 디렉토리의 docker-compose.yml로 이미지 빌드(기준 디렉토리 주의)

########################################################################
#                        stage-0 : 리액트 빌드
########################################################################
FROM node:18.8.0

WORKDIR /usr/src/app

COPY . .

RUN npm run build

########################################################################
#                        stage-1 : Nginx로 배포
########################################################################
FROM nginx:1.21.6-alpine

# state:0에서 빌드된 파일을 /var/www/http 로 가져오기
COPY --from=0 /usr/src/app/web/build /var/www/http

# Nginx 설정파일 복제
COPY ./web/nginx.conf /etc/nginx/conf.d/default.conf

# Nginx 포그라운드 실행
CMD ["nginx", "-g",  "daemon off;"]